### ISSUE TITLE
version compatibility

### ISSUE THREAD

**Issue by bigmittens** [wm4/mpv-scripts#1]
very minor issue, maybe more of a question.

auto-profiles.lua opens with a comment saying `mpv 0.22.0 is required`. From testing, it seems that script works properly with the current release of mpv, 0.21.0.

Is the script fully compatible with the current version, or have some requirements not been merged yet?

**Comment by wm4** [comment]
I got the version number wrong, 0.21.0 is correct. Fixed it.
