### ISSUE TITLE
script-opts not working

### ISSUE THREAD

**Issue by Vyral-Protoss** [wm4/mpv-scripts#2]
Concerns the auto-profiles.lua script.
In my mpv.conf, inside the "protocol.https" profile, I've put "script-opts=auto-profiles=no" (I've also tried "script-opts=no-auto-profiles=true" from Haasn mpv.conf) so the other profiles I've defined for other videos are not loaded. As expected, the "protocol.https" profile is loaded first, yet after that, auto-profiles keeps loading other profiles.
My mpv.conf : 
https://raw.githubusercontent.com/Vyral-Protoss/Complete-MPV-Conf/master/mpv.conf

**Comment by Vyral-Protoss** [comment]
Cmd output : 
http://i.imgur.com/hc8Jfdv.png

**Comment by wm4** [comment]
This didn't work because the script checks script-opts on early start only. I've changed it to make it check it at runtime, but there's no guarantee it will work as intended. If it doesn't, you're out of luck. Using auto-profiles in this way is a bit sketchy.
