### ISSUE TITLE
attempt to compare nil with number, attempt to compare number with nil

### ISSUE THREAD

**Issue by JulianLai** [wm4/mpv-scripts#7]
These are two of the settings in my mpv.conf
```
[4K]
profile-desc=cond:p.height>2160
hwdec=vaapi
```
```
[SD]
profile-desc=cond:p.height<=480
hwdec=vdpau-copy
scale=ewa_lanczos
profile=opengl-hq
```
It says that [auto_profiles] Error evaluating: [string "profile SD condition"]:1: attempt to compare nil with number and [auto_profiles] Error evaluating: [string "profile 4K condition"]:1: attempt to compare number with nil.

**Comment by garoto** [comment]
I saw this in someone .conf file (rossy? haasn? cant recall):

`profile-desc=cond:get("height", math.huge) <= 480`

Works for me.

**Comment by JulianLai** [comment]
@garoto The syntax is so complicated...

**Comment by JulianLai** [comment]
@garoto Thanks, I didn't know that I can add an 'and' after it either, now it works!

**Comment by zc62** [comment]
`profile-desc=cond:p["video-params/h"]<=480`
